# Generated by Django 3.2.5 on 2021-07-28 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offer", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="likers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="offer",
            name="categories",
            field=models.ManyToManyField(related_name="offers", to="offer.Category"),
        ),
        migrations.AddField(
            model_name="offer",
            name="store",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="offer.store",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="types",
            field=models.ManyToManyField(related_name="offers", to="offer.Type"),
        ),
        migrations.AddField(
            model_name="offer",
            name="users",
            field=models.ManyToManyField(
                related_name="offers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
