# Generated by Django 3.2.6 on 2021-08-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(null=True)),
                ("viewed", models.BooleanField(default=False)),
                ("json_data", models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
